import './globals.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import NavList from "./NavList";

config.autoAddCss = false;

export const metadata = {
  title: 'Movies App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <NavList />
          </nav>
        {children}
        </main>
      </body>
    </html>
  )
}
