import Link from "next/link";
import './globals.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

export const metadata = {
  title: 'Movies App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav className="nav-list">
            <Link href="/" className="nav-item">Movies</Link>
            <Link href="/profile" className="nav-item">Profile</Link>
          </nav>
        {children}
        </main>
      </body>
    </html>
  )
}
